### ISSUE TITLE
红米note3 8.1.0系统,当进入SmartActivity以后,点击Home键返回到桌面,直接崩溃

### ISSUE THREAD

**Issue by lydlovezjr** [PrototypeZ/SaveState#1]
01-01 01:03:52.450 12866-12866/savestate.prototype.github.io.savestate E/AndroidRuntime: FATAL EXCEPTION: main
    Process: savestate.prototype.github.io.savestate, PID: 12866
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at io.github.prototypez.savestate.activity.SmartActivityAutoSaveState.onSaveInstanceState(SmartActivityAutoSaveState.java:10)
        at io.github.prototypez.savestate.activity.SmartActivity.onSaveInstanceState(Unknown Source:19)
        at android.app.Activity.performSaveInstanceState(Activity.java:1501)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4722)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4026)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4085)
        at android.app.ActivityThread.-wrap24(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by PrototypeZ** [comment]
Thanks for reporting this issue! It's fixed in version 0.1.4.
